# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotedash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qutoes',
            name='author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qutoes',
            name='quote',
            field=models.TextField(max_length=255),
        ),
    ]
