# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotedash', '0002_auto_20180626_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qutoes',
            new_name='Quotes',
        ),
    ]
