# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotedash', '0004_auto_20180626_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='likecount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
