# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotedash', '0005_quotes_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='likecount',
            field=models.IntegerField(blank=True),
        ),
    ]
